#!/usr/bin/env python
print "Set-Cookie:username = ;"
print "Content-Type: text/html\r\n\r\n"
print "<html>"
print "<head>"
print "<title>Session Destroyed</title>"
print "</head>"
print "<body>"
print "<h1>Session Destroyed</h1>"
print "<p><a href='../python-start-demo.html'>CGI Form</a></p>"
print "<p><a href='python-session1.py'>Session Page 1</a></p>"
print "<p><a href='python-session2.py'>Session Page 2</a></p>"
print "</body>"
print "</html>"

